/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idManager.h"


void
idmanager_1(char *host)
{
	CLIENT *clnt;
	idResult  *result_1;
	struct information  register_1_arg;
	idResult  *result_2;
	char *get_registered_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, IDMANAGER, FIRST, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = register_1(&register_1_arg, clnt);
	if (result_1 == (idResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = get_registered_1((void*)&get_registered_1_arg, clnt);
	if (result_2 == (idResult *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	idmanager_1 (host);
exit (0);
}
