/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "caesar.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

caesar_output *
encode_1(caesar_input *argp, CLIENT *clnt)
{
	static caesar_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, encode,
		(xdrproc_t) xdr_caesar_input, (caddr_t) argp,
		(xdrproc_t) xdr_caesar_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

caesar_output *
decode_1(caesar_input *argp, CLIENT *clnt)
{
	static caesar_output clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, decode,
		(xdrproc_t) xdr_caesar_input, (caddr_t) argp,
		(xdrproc_t) xdr_caesar_output, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
