/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAESAR_H_RPCGEN
#define _CAESAR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_TEXT_LENGTH 256

struct caesar_output {
	int ret_code;
	union {
		char text[MAX_TEXT_LENGTH];
	} caesar_output_u;
};
typedef struct caesar_output caesar_output;

struct caesar_input {
	char text[MAX_TEXT_LENGTH];
	short shift;
};
typedef struct caesar_input caesar_input;

#define CAESAR 0x20000098
#define VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define encode 1
extern  caesar_output * encode_1(caesar_input *, CLIENT *);
extern  caesar_output * encode_1_svc(caesar_input *, struct svc_req *);
#define decode 2
extern  caesar_output * decode_1(caesar_input *, CLIENT *);
extern  caesar_output * decode_1_svc(caesar_input *, struct svc_req *);
extern int caesar_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define encode 1
extern  caesar_output * encode_1();
extern  caesar_output * encode_1_svc();
#define decode 2
extern  caesar_output * decode_1();
extern  caesar_output * decode_1_svc();
extern int caesar_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_caesar_output (XDR *, caesar_output*);
extern  bool_t xdr_caesar_input (XDR *, caesar_input*);

#else /* K&R C */
extern bool_t xdr_caesar_output ();
extern bool_t xdr_caesar_input ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CAESAR_H_RPCGEN */
