/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "caesar.h"

bool_t
xdr_caesar_output (XDR *xdrs, caesar_output *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ret_code))
		 return FALSE;
	switch (objp->ret_code) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->caesar_output_u.text, MAX_TEXT_LENGTH,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_caesar_input (XDR *xdrs, caesar_input *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->text, MAX_TEXT_LENGTH,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_short (xdrs, &objp->shift))
		 return FALSE;
	return TRUE;
}
