/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDMANAGER_H_RPCGEN
#define _IDMANAGER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAX_NAME_SIZE 128

struct information {
	char nombre[MAX_NAME_SIZE];
};
typedef struct information information;

struct request {
	long id;
	char nombre[MAX_NAME_SIZE];
};
typedef struct request request;
#define MAX_MESSAGE_SIZE 512

struct infoResult {
	int cod_ret;
	union {
		struct information data;
		char message[MAX_MESSAGE_SIZE];
	} infoResult_u;
};
typedef struct infoResult infoResult;

struct idResult {
	int cod_ret;
	union {
		long id;
		char message[MAX_MESSAGE_SIZE];
	} idResult_u;
};
typedef struct idResult idResult;

#define IDMANAGER 0x20000099
#define FIRST 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER 1
extern  idResult * register_1(struct information *, CLIENT *);
extern  idResult * register_1_svc(struct information *, struct svc_req *);
#define GET_REGISTERED 2
extern  idResult * get_registered_1(void *, CLIENT *);
extern  idResult * get_registered_1_svc(void *, struct svc_req *);
extern int idmanager_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER 1
extern  idResult * register_1();
extern  idResult * register_1_svc();
#define GET_REGISTERED 2
extern  idResult * get_registered_1();
extern  idResult * get_registered_1_svc();
extern int idmanager_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_information (XDR *, information*);
extern  bool_t xdr_request (XDR *, request*);
extern  bool_t xdr_infoResult (XDR *, infoResult*);
extern  bool_t xdr_idResult (XDR *, idResult*);

#else /* K&R C */
extern bool_t xdr_information ();
extern bool_t xdr_request ();
extern bool_t xdr_infoResult ();
extern bool_t xdr_idResult ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDMANAGER_H_RPCGEN */
