/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "idManager.h"

idResult *
register_1_svc(struct information *argp, struct svc_req *rqstp)
{
	static idResult  result;

	/*
	 * insert server code here
	 */

	return &result;
}

idResult *
get_registered_1_svc(void *argp, struct svc_req *rqstp)
{
	static idResult  result;

	/*
	 * insert server code here
	 */

	return &result;
}
