/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "idManager.h"

bool_t
xdr_errorCodes (XDR *xdrs, errorCodes *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_registerResult (XDR *xdrs, registerResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 0:
		 if (!xdr_long (xdrs, &objp->registerResult_u.mtype))
			 return FALSE;
		break;
	case -1:
		 if (!xdr_errorCodes (xdrs, &objp->registerResult_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_queryResult (XDR *xdrs, queryResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 0:
		 if (!xdr_array (xdrs, (char **)&objp->queryResult_u.mtype.mtype_val, (u_int *) &objp->queryResult_u.mtype.mtype_len, ~0,
			sizeof (long), (xdrproc_t) xdr_long))
			 return FALSE;
		break;
	case -1:
		 if (!xdr_errorCodes (xdrs, &objp->queryResult_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_getResult (XDR *xdrs, getResult *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->cod_ret))
		 return FALSE;
	switch (objp->cod_ret) {
	case 0:
		 if (!xdr_vector (xdrs, (char *)objp->getResult_u.address, MAX_ADDRESS_LENGTH,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		break;
	case -1:
		 if (!xdr_errorCodes (xdrs, &objp->getResult_u.error))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
