/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "idManager.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

registerResult *
register_1(void *argp, CLIENT *clnt)
{
	static registerResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, REGISTER,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_registerResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

queryResult *
query_1(void *argp, CLIENT *clnt)
{
	static queryResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, QUERY,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_queryResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

getResult *
get_1(long *argp, CLIENT *clnt)
{
	static getResult clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, GET,
		(xdrproc_t) xdr_long, (caddr_t) argp,
		(xdrproc_t) xdr_getResult, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
