/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <arpa/inet.h>
#include <stdio.h>
#include "idManager.h"

struct hostInfo
{
    char address[MAX_ADDRESS_LENGTH];
    long mtype;
};

registerResult *
register_1_svc(void *nothing, struct svc_req *rqstp)
{
    static registerResult result;
    long mtype = 1;
    struct hostInfo host;
    FILE * file;

    // find the next available mtype
    file = fopen("ids.dat", "rb");
    if (file) {
        do {
            fread(&host, sizeof (host), 1, file);
        } while (!feof(file) && host.mtype == mtype++);
        fclose(file);
    }

    // add the mtype to the file
    file = fopen("ids.dat", "ab");
    strncpy(host.address, inet_ntoa(rqstp->rq_xprt->xp_raddr.sin_addr), MAX_ADDRESS_LENGTH);
    host.mtype = mtype;
    fwrite(&host, sizeof (host), 1, file);
    fclose(file);

    printf("REGISTER %3ld as %s\n", mtype, host.address);
    result.cod_ret = 0;
    result.registerResult_u.mtype = mtype;

    return &result;
}

queryResult *
query_1_svc(void *nothing, struct svc_req *rqstp)
{
    static queryResult result;

    struct hostInfo host;
    long * list = NULL;
    unsigned length = 0, current = 0;
    printf("QUERY: ");
    FILE * file = fopen("ids.dat", "rb");
    if (file) {
        do {
            fread(&host, sizeof (host), 1, file);
            if (!feof(file)) {
                if (current >= length) {
                    if (length == 0) {
                        length = 1;
                        list = (long*) malloc(sizeof (long));
                    } else {
                        length *= 2;
                        list = (long*) realloc(list, sizeof (long) * length);
                    }
                }
                list[current] = host.mtype;
                current++;
                printf("%3ld ", host.mtype);
            }
        } while (!feof(file));
        fclose(file);
        printf("\n");
        if (length) {
            list = (long*) realloc(list, sizeof (long) *(current));
        }
    }
    result.cod_ret = 0;
    result.queryResult_u.mtype.mtype_len = current;
    result.queryResult_u.mtype.mtype_val = list;

    return &result;
}

getResult *
get_1_svc(long *mtype, struct svc_req *rqstp)
{
    static getResult result;

    static struct hostInfo host;
    FILE * file = fopen("ids.dat", "rb");
    host.mtype = 0;
    if (file) {
        do {
            fread(&host, sizeof (host), 1, file);
        } while (!feof(file) && host.mtype != *mtype);
        if (feof(file)) {
            host.mtype = 0;
        }
        fclose(file);

        if (host.mtype) {
            result.cod_ret = 0;
            strncpy(result.getResult_u.address, host.address, MAX_ADDRESS_LENGTH);
            printf("GET %3ld is %s\n", host.mtype, host.address);
        } else {
            result.cod_ret = -1;
            result.getResult_u.error = INVIALID_ID;
        }
    } else {
        result.cod_ret = -1;
        result.getResult_u.error = FILE_ACCESS_FAILURE;
    }

    return &result;
}
